/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i
//
// C11 language lexer.
// Reference: https://quut.com/c/ANSI-C-grammar-l-2011.html

#include <assert.h>
#include <stdio.h>

constexpr bool DEBUG = false;

#define PRINT_TOKEN(token) do { \
  if (DEBUG) printf("token = [%s]\n", token); \
} while(0)

#define PRINT_TOKEN2(start, size) do { \
  if (DEBUG) printf("token = [%.*s]\n", (int)(size), token); \
} while(0)

bool lex(const char *source) {
  const char *YYCURSOR = source;
  const char *YYMARKER = source;

  while(true){
    const char* token = YYCURSOR;
  
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ': goto yy4;
		case '!': goto yy6;
		case '"': goto yy8;
		case '#': goto yy9;
		case '%': goto yy10;
		case '&': goto yy12;
		case '\'': goto yy14;
		case '(': goto yy15;
		case ')': goto yy16;
		case '*': goto yy17;
		case '+': goto yy19;
		case ',': goto yy21;
		case '-': goto yy22;
		case '.': goto yy24;
		case '/': goto yy26;
		case '0': goto yy28;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy30;
		case ':': goto yy32;
		case ';': goto yy34;
		case '<': goto yy35;
		case '=': goto yy37;
		case '>': goto yy39;
		case '?': goto yy41;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		case 'L':
		case 'U': goto yy45;
		case '[': goto yy46;
		case '\\': goto yy47;
		case ']': goto yy48;
		case '^': goto yy49;
		case '_': goto yy51;
		case 'a': goto yy52;
		case 'b': goto yy53;
		case 'c': goto yy54;
		case 'd': goto yy55;
		case 'e': goto yy56;
		case 'f': goto yy57;
		case 'g': goto yy58;
		case 'i': goto yy59;
		case 'l': goto yy60;
		case 'r': goto yy61;
		case 's': goto yy62;
		case 't': goto yy63;
		case 'u': goto yy64;
		case 'v': goto yy65;
		case 'w': goto yy66;
		case '{': goto yy67;
		case '|': goto yy68;
		case '}': goto yy70;
		case '~': goto yy71;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
	{ return true; }
yy2:
	++YYCURSOR;
yy3:
	{ printf("[Error] unknown char = [%d]\n", yych); return false; }
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
	{ continue; }
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy72;
		default: goto yy7;
	}
yy7:
	{ PRINT_TOKEN("!"); continue; }
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 0x00:
		case '\n': goto yy3;
		default: goto yy74;
	}
yy9:
	++YYCURSOR;
	{ PRINT_TOKEN("#"); continue; }
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy79;
		case '>': goto yy70;
		default: goto yy11;
	}
yy11:
	{ PRINT_TOKEN("%"); continue; }
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
		case '&': goto yy80;
		case '=': goto yy81;
		default: goto yy13;
	}
yy13:
	{ PRINT_TOKEN("&"); continue; }
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 0x00:
		case '\n':
		case '\'': goto yy3;
		default: goto yy83;
	}
yy15:
	++YYCURSOR;
	{ PRINT_TOKEN("("); continue; }
yy16:
	++YYCURSOR;
	{ PRINT_TOKEN(")"); continue; }
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy85;
		default: goto yy18;
	}
yy18:
	{ PRINT_TOKEN("*"); continue; }
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+': goto yy86;
		case '=': goto yy87;
		default: goto yy20;
	}
yy20:
	{ PRINT_TOKEN("+"); continue; }
yy21:
	++YYCURSOR;
	{ PRINT_TOKEN(","); continue; }
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy88;
		case '=': goto yy89;
		case '>': goto yy90;
		default: goto yy23;
	}
yy23:
	{ PRINT_TOKEN("-"); continue; }
yy24:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy91;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		default: goto yy25;
	}
yy25:
	{ PRINT_TOKEN("."); continue; }
yy26:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '*': goto yy94;
		case '/': goto yy95;
		case '=': goto yy96;
		default: goto yy27;
	}
yy27:
	{ PRINT_TOKEN("/"); continue; }
yy28:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'X':
		case 'x': goto yy105;
		default: goto yy100;
	}
yy29:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy30:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy97;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy30;
		case 'E':
		case 'e': goto yy102;
		case 'L': goto yy107;
		case 'U':
		case 'u': goto yy108;
		case 'l': goto yy109;
		default: goto yy31;
	}
yy31:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy48;
		default: goto yy33;
	}
yy33:
	{ PRINT_TOKEN(":"); continue; }
yy34:
	++YYCURSOR;
	{ PRINT_TOKEN(";"); continue; }
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case '%': goto yy67;
		case ':': goto yy46;
		case '<': goto yy110;
		case '=': goto yy112;
		default: goto yy36;
	}
yy36:
	{ PRINT_TOKEN("<"); continue; }
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy113;
		default: goto yy38;
	}
yy38:
	{ PRINT_TOKEN("="); continue; }
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy114;
		case '>': goto yy115;
		default: goto yy40;
	}
yy40:
	{ PRINT_TOKEN(">"); continue; }
yy41:
	++YYCURSOR;
	{ PRINT_TOKEN("?"); continue; }
yy42:
	yych = *++YYCURSOR;
yy43:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy44;
	}
yy44:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy45:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '"': goto yy73;
		case '\'': goto yy117;
		default: goto yy43;
	}
yy46:
	++YYCURSOR;
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy47:
	++YYCURSOR;
	{ PRINT_TOKEN("\\"); continue; }
yy48:
	++YYCURSOR;
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy118;
		default: goto yy50;
	}
yy50:
	{ PRINT_TOKEN("^"); continue; }
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A': goto yy119;
		case 'B': goto yy120;
		case 'C': goto yy121;
		case 'G': goto yy122;
		case 'I': goto yy123;
		case 'N': goto yy124;
		case 'S': goto yy125;
		case 'T': goto yy126;
		case '_': goto yy127;
		default: goto yy43;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy128;
		default: goto yy43;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy129;
		default: goto yy43;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy130;
		case 'h': goto yy131;
		case 'o': goto yy132;
		default: goto yy43;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy133;
		case 'o': goto yy134;
		default: goto yy43;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy136;
		case 'n': goto yy137;
		case 'x': goto yy138;
		default: goto yy43;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy139;
		case 'o': goto yy140;
		default: goto yy43;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy141;
		default: goto yy43;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy142;
		case 'n': goto yy144;
		default: goto yy43;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy145;
		default: goto yy43;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy146;
		default: goto yy43;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy147;
		case 'i': goto yy148;
		case 't': goto yy149;
		case 'w': goto yy150;
		default: goto yy43;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy151;
		default: goto yy43;
	}
yy64:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '"': goto yy73;
		case '\'': goto yy117;
		case '8': goto yy152;
		case 'n': goto yy153;
		default: goto yy43;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy154;
		default: goto yy43;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy155;
		default: goto yy43;
	}
yy67:
	++YYCURSOR;
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy156;
		case '|': goto yy157;
		default: goto yy69;
	}
yy69:
	{ PRINT_TOKEN("|"); continue; }
yy70:
	++YYCURSOR;
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy71:
	++YYCURSOR;
	{ PRINT_TOKEN("~"); continue; }
yy72:
	++YYCURSOR;
	{ PRINT_TOKEN("!="); continue; }
yy73:
	yych = *++YYCURSOR;
yy74:
	switch (yych) {
		case 0x00:
		case '\n': goto yy75;
		case '"': goto yy76;
		case '\\': goto yy78;
		default: goto yy73;
	}
yy75:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy3;
		case 1: goto yy25;
		case 2: goto yy27;
		case 3: goto yy29;
		case 4: goto yy31;
		case 5: goto yy44;
		case 6: goto yy77;
		case 7: goto yy93;
		case 8: goto yy98;
		default: goto yy177;
	}
yy76:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case ' ': goto yy76;
		case '"': goto yy73;
		case 'L':
		case 'U': goto yy158;
		case 'u': goto yy159;
		default: goto yy77;
	}
yy77:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"':
		case '\'':
		case '\\':
		case 'a':
		case 'b':
		case 'f':
		case 'n':
		case 'r':
		case 't':
		case 'v': goto yy73;
		default: goto yy75;
	}
yy79:
	++YYCURSOR;
	{ PRINT_TOKEN("%="); continue; }
yy80:
	++YYCURSOR;
	{ PRINT_TOKEN("&&"); continue; }
yy81:
	++YYCURSOR;
	{ PRINT_TOKEN("&="); continue; }
yy82:
	yych = *++YYCURSOR;
yy83:
	switch (yych) {
		case 0x00:
		case '\n': goto yy75;
		case '\'': goto yy160;
		case '\\': goto yy84;
		default: goto yy82;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"':
		case '\'':
		case '\\':
		case 'a':
		case 'b':
		case 'f':
		case 'n':
		case 'r':
		case 't':
		case 'v': goto yy82;
		default: goto yy75;
	}
yy85:
	++YYCURSOR;
	{ PRINT_TOKEN("*="); continue; }
yy86:
	++YYCURSOR;
	{ PRINT_TOKEN("++"); continue; }
yy87:
	++YYCURSOR;
	{ PRINT_TOKEN("+="); continue; }
yy88:
	++YYCURSOR;
	{ PRINT_TOKEN("--"); continue; }
yy89:
	++YYCURSOR;
	{ PRINT_TOKEN("-="); continue; }
yy90:
	++YYCURSOR;
	{ PRINT_TOKEN("->"); continue; }
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy161;
		default: goto yy75;
	}
yy92:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		case 'E':
		case 'e': goto yy162;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy163;
		default: goto yy93;
	}
yy93:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy75;
		case '*': goto yy164;
		default: goto yy94;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy75;
		case '\n': goto yy165;
		default: goto yy95;
	}
yy96:
	++YYCURSOR;
	{ PRINT_TOKEN("/="); continue; }
yy97:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		case 'E':
		case 'e': goto yy166;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy167;
		default: goto yy98;
	}
yy98:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy99:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
yy100:
	switch (yych) {
		case '.': goto yy97;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy99;
		case '8':
		case '9': goto yy101;
		case 'E':
		case 'e': goto yy102;
		case 'L': goto yy103;
		case 'U':
		case 'u': goto yy104;
		case 'l': goto yy106;
		default: goto yy29;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy97;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy101;
		case 'E':
		case 'e': goto yy102;
		default: goto yy75;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy168;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy169;
		default: goto yy75;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy171;
		case 'U':
		case 'u': goto yy172;
		default: goto yy29;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy173;
		case 'l': goto yy174;
		default: goto yy29;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy175;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy176;
		default: goto yy75;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy172;
		case 'l': goto yy171;
		default: goto yy29;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy178;
		case 'U':
		case 'u': goto yy179;
		default: goto yy31;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy180;
		case 'l': goto yy181;
		default: goto yy31;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy179;
		case 'l': goto yy178;
		default: goto yy31;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy182;
		default: goto yy111;
	}
yy111:
	{ PRINT_TOKEN("<<"); continue; }
yy112:
	++YYCURSOR;
	{ PRINT_TOKEN("<="); continue; }
yy113:
	++YYCURSOR;
	{ PRINT_TOKEN("=="); continue; }
yy114:
	++YYCURSOR;
	{ PRINT_TOKEN(">="); continue; }
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy183;
		default: goto yy116;
	}
yy116:
	{ PRINT_TOKEN(">>"); continue; }
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy75;
		default: goto yy83;
	}
yy118:
	++YYCURSOR;
	{ PRINT_TOKEN("^="); continue; }
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy184;
		case 't': goto yy185;
		default: goto yy43;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy186;
		default: goto yy43;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy187;
		default: goto yy43;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy188;
		default: goto yy43;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'm': goto yy189;
		default: goto yy43;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy190;
		default: goto yy43;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy191;
		default: goto yy43;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy192;
		default: goto yy43;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy193;
		default: goto yy43;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy194;
		default: goto yy43;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy195;
		default: goto yy43;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy196;
		default: goto yy43;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy197;
		default: goto yy43;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy198;
		default: goto yy43;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy199;
		default: goto yy43;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		case 'u': goto yy200;
		default: goto yy135;
	}
yy135:
	{ PRINT_TOKEN("do"); continue; }
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy201;
		default: goto yy43;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy202;
		default: goto yy43;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy203;
		default: goto yy43;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy204;
		default: goto yy43;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy205;
		default: goto yy43;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy207;
		default: goto yy43;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy143;
	}
yy143:
	{ PRINT_TOKEN("if"); continue; }
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy208;
		case 't': goto yy209;
		default: goto yy43;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy211;
		default: goto yy43;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy212;
		case 's': goto yy213;
		case 't': goto yy214;
		default: goto yy43;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy215;
		default: goto yy43;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy216;
		case 'z': goto yy217;
		default: goto yy43;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy218;
		case 'r': goto yy219;
		default: goto yy43;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy220;
		default: goto yy43;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy221;
		default: goto yy43;
	}
yy152:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '"': goto yy73;
		default: goto yy43;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy222;
		case 's': goto yy223;
		default: goto yy43;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy224;
		case 'l': goto yy225;
		default: goto yy43;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy226;
		default: goto yy43;
	}
yy156:
	++YYCURSOR;
	{ PRINT_TOKEN("|="); continue; }
yy157:
	++YYCURSOR;
	{ PRINT_TOKEN("||"); continue; }
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy73;
		default: goto yy75;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy73;
		case '8': goto yy158;
		default: goto yy75;
	}
yy160:
	++YYCURSOR;
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy161:
	++YYCURSOR;
	{ PRINT_TOKEN("..."); continue; }
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy227;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy228;
		default: goto yy75;
	}
yy163:
	++YYCURSOR;
	goto yy93;
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy75;
		case '/': goto yy229;
		default: goto yy94;
	}
yy165:
	++YYCURSOR;
	{ continue; }
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy230;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy231;
		default: goto yy75;
	}
yy167:
	++YYCURSOR;
	goto yy98;
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy169;
		default: goto yy75;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy169;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy232;
		default: goto yy170;
	}
yy170:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy172;
		default: goto yy29;
	}
yy172:
	++YYCURSOR;
	goto yy29;
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy172;
		default: goto yy29;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy172;
		default: goto yy29;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'P':
		case 'p': goto yy75;
		default: goto yy234;
	}
yy176:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy235;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy176;
		case 'L': goto yy236;
		case 'P':
		case 'p': goto yy237;
		case 'U':
		case 'u': goto yy238;
		case 'l': goto yy239;
		default: goto yy177;
	}
yy177:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy179;
		default: goto yy31;
	}
yy179:
	++YYCURSOR;
	goto yy31;
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy179;
		default: goto yy31;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy179;
		default: goto yy31;
	}
yy182:
	++YYCURSOR;
	{ PRINT_TOKEN("<<="); continue; }
yy183:
	++YYCURSOR;
	{ PRINT_TOKEN(">>="); continue; }
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy240;
		default: goto yy43;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy241;
		default: goto yy43;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy242;
		default: goto yy43;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'm': goto yy243;
		default: goto yy43;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy244;
		default: goto yy43;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy245;
		default: goto yy43;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy246;
		default: goto yy43;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy247;
		default: goto yy43;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy248;
		default: goto yy43;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy249;
		default: goto yy43;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy250;
		default: goto yy43;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy252;
		default: goto yy43;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy253;
		default: goto yy43;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy255;
		default: goto yy43;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy257;
		case 't': goto yy258;
		default: goto yy43;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy259;
		default: goto yy43;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'b': goto yy260;
		default: goto yy43;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy261;
		default: goto yy43;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'm': goto yy263;
		default: goto yy43;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy265;
		default: goto yy43;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy266;
		default: goto yy43;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy206;
	}
yy206:
	{ PRINT_TOKEN("for"); continue; }
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy267;
		default: goto yy43;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy269;
		default: goto yy43;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy210;
	}
yy210:
	{ PRINT_TOKEN("int"); continue; }
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy270;
		default: goto yy43;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy272;
		default: goto yy43;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy273;
		default: goto yy43;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy274;
		default: goto yy43;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy275;
		default: goto yy43;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy276;
		default: goto yy43;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy277;
		default: goto yy43;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy278;
		default: goto yy43;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy279;
		default: goto yy43;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy280;
		default: goto yy43;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy281;
		default: goto yy43;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy282;
		default: goto yy43;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy283;
		default: goto yy43;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy284;
		default: goto yy43;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy286;
		default: goto yy43;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy287;
		default: goto yy43;
	}
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy228;
		default: goto yy75;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy228;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy163;
		default: goto yy93;
	}
yy229:
	++YYCURSOR;
	{ continue; }
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy231;
		default: goto yy75;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy231;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy167;
		default: goto yy98;
	}
yy232:
	++YYCURSOR;
	goto yy170;
yy233:
	yych = *++YYCURSOR;
yy234:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy233;
		case 'P':
		case 'p': goto yy288;
		default: goto yy75;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'P':
		case 'p': goto yy289;
		default: goto yy234;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy290;
		case 'U':
		case 'u': goto yy291;
		default: goto yy177;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy292;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy293;
		default: goto yy75;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy295;
		case 'l': goto yy296;
		default: goto yy177;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy291;
		case 'l': goto yy290;
		default: goto yy177;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy297;
		default: goto yy43;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'm': goto yy298;
		default: goto yy43;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy299;
		default: goto yy43;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy301;
		default: goto yy43;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy302;
		default: goto yy43;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy303;
		default: goto yy43;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy304;
		default: goto yy43;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy305;
		default: goto yy43;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy306;
		default: goto yy43;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy307;
		default: goto yy43;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy251;
	}
yy251:
	{ PRINT_TOKEN("auto"); continue; }
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'k': goto yy308;
		default: goto yy43;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy254;
	}
yy254:
	{ PRINT_TOKEN("case"); continue; }
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy256;
	}
yy256:
	{ PRINT_TOKEN("char"); continue; }
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy310;
		default: goto yy43;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy312;
		default: goto yy43;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy313;
		default: goto yy43;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy314;
		default: goto yy43;
	}
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy262;
	}
yy262:
	{ PRINT_TOKEN("else"); continue; }
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy264;
	}
yy264:
	{ PRINT_TOKEN("enum"); continue; }
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy315;
		default: goto yy43;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy316;
		default: goto yy43;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy268;
	}
yy268:
	{ PRINT_TOKEN("goto"); continue; }
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy318;
		default: goto yy43;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy271;
	}
yy271:
	{ PRINT_TOKEN("long"); continue; }
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy319;
		default: goto yy43;
	}
yy273:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy320;
		default: goto yy43;
	}
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy321;
		default: goto yy43;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy322;
		default: goto yy43;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy324;
		default: goto yy43;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy325;
		default: goto yy43;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy326;
		default: goto yy43;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy327;
		default: goto yy43;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy328;
		default: goto yy43;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy329;
		default: goto yy43;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy330;
		default: goto yy43;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy332;
		default: goto yy43;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy285;
	}
yy285:
	{ PRINT_TOKEN("void"); continue; }
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy333;
		default: goto yy43;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy334;
		default: goto yy43;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy336;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy337;
		default: goto yy75;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy339;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy340;
		default: goto yy75;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U':
		case 'u': goto yy291;
		default: goto yy177;
	}
yy291:
	++YYCURSOR;
	goto yy177;
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy293;
		default: goto yy75;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy293;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy342;
		default: goto yy294;
	}
yy294:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy291;
		default: goto yy177;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy291;
		default: goto yy177;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy343;
		default: goto yy43;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy344;
		default: goto yy43;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy300;
	}
yy300:
	{ PRINT_TOKEN("_Bool"); continue; }
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy345;
		default: goto yy43;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy346;
		default: goto yy43;
	}
yy303:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy347;
		default: goto yy43;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy348;
		default: goto yy43;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy349;
		default: goto yy43;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy350;
		default: goto yy43;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy351;
		default: goto yy43;
	}
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy309;
	}
yy309:
	{ PRINT_TOKEN("break"); continue; }
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy311;
	}
yy311:
	{ PRINT_TOKEN("const"); continue; }
yy312:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy352;
		default: goto yy43;
	}
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy353;
		default: goto yy43;
	}
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy354;
		default: goto yy43;
	}
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy356;
		default: goto yy43;
	}
yy316:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy317;
	}
yy317:
	{ PRINT_TOKEN("float"); continue; }
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy358;
		default: goto yy43;
	}
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy360;
		default: goto yy43;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy361;
		default: goto yy43;
	}
yy321:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy362;
		default: goto yy43;
	}
yy322:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy323;
	}
yy323:
	{ PRINT_TOKEN("short"); continue; }
yy324:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy364;
		default: goto yy43;
	}
yy325:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy366;
		default: goto yy43;
	}
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy368;
		default: goto yy43;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy370;
		default: goto yy43;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy372;
		default: goto yy43;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy374;
		default: goto yy43;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy331;
	}
yy331:
	{ PRINT_TOKEN("union"); continue; }
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy375;
		default: goto yy43;
	}
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy376;
		default: goto yy43;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy335;
	}
yy335:
	{ PRINT_TOKEN("while"); continue; }
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy337;
		default: goto yy75;
	}
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy337;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy377;
		default: goto yy338;
	}
yy338:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy339:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy340;
		default: goto yy75;
	}
yy340:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy340;
		case 'F':
		case 'L':
		case 'f':
		case 'l': goto yy378;
		default: goto yy341;
	}
yy341:
	{ PRINT_TOKEN2(token, YYCURSOR - token); continue; }
yy342:
	++YYCURSOR;
	goto yy294;
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy379;
		case 'o': goto yy380;
		default: goto yy43;
	}
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy381;
		default: goto yy43;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy383;
		default: goto yy43;
	}
yy346:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy384;
		default: goto yy43;
	}
yy347:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy385;
		default: goto yy43;
	}
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy386;
		default: goto yy43;
	}
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy387;
		default: goto yy43;
	}
yy350:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy388;
		default: goto yy43;
	}
yy351:
	yych = *++YYCURSOR;
	switch (yych) {
		case '_': goto yy389;
		default: goto yy43;
	}
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy390;
		default: goto yy43;
	}
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy391;
		default: goto yy43;
	}
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy355;
	}
yy355:
	{ PRINT_TOKEN("double"); continue; }
yy356:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy357;
	}
yy357:
	{ PRINT_TOKEN("extern"); continue; }
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy359;
	}
yy359:
	{ PRINT_TOKEN("inline"); continue; }
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy393;
		default: goto yy43;
	}
yy361:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy394;
		default: goto yy43;
	}
yy362:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy363;
	}
yy363:
	{ PRINT_TOKEN("return"); continue; }
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy365;
	}
yy365:
	{ PRINT_TOKEN("signed"); continue; }
yy366:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy367;
	}
yy367:
	{ PRINT_TOKEN("sizeof"); continue; }
yy368:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy369;
	}
yy369:
	{ PRINT_TOKEN("static"); continue; }
yy370:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy371;
	}
yy371:
	{ PRINT_TOKEN("struct"); continue; }
yy372:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy373;
	}
yy373:
	{ PRINT_TOKEN("switch"); continue; }
yy374:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy395;
		default: goto yy43;
	}
yy375:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy397;
		default: goto yy43;
	}
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy398;
		default: goto yy43;
	}
yy377:
	++YYCURSOR;
	goto yy338;
yy378:
	++YYCURSOR;
	goto yy341;
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy399;
		default: goto yy43;
	}
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy401;
		default: goto yy43;
	}
yy381:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy382;
	}
yy382:
	{ PRINT_TOKEN("_Atomic"); continue; }
yy383:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'x': goto yy403;
		default: goto yy43;
	}
yy384:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy405;
		default: goto yy43;
	}
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy407;
		default: goto yy43;
	}
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy408;
		default: goto yy43;
	}
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
		case '_': goto yy409;
		default: goto yy43;
	}
yy388:
	yych = *++YYCURSOR;
	switch (yych) {
		case '_': goto yy410;
		default: goto yy43;
	}
yy389:
	yych = *++YYCURSOR;
	switch (yych) {
		case '_': goto yy411;
		default: goto yy43;
	}
yy390:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy413;
		default: goto yy43;
	}
yy391:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy392;
	}
yy392:
	{ PRINT_TOKEN("default"); continue; }
yy393:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy415;
		default: goto yy43;
	}
yy394:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy417;
		default: goto yy43;
	}
yy395:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy396;
	}
yy396:
	{ PRINT_TOKEN("typedef"); continue; }
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy419;
		default: goto yy43;
	}
yy398:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy421;
		default: goto yy43;
	}
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy400;
	}
yy400:
	{ PRINT_TOKEN("_Alignas"); continue; }
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy402;
	}
yy402:
	{ PRINT_TOKEN("_Alignof"); continue; }
yy403:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy404;
	}
yy404:
	{ PRINT_TOKEN("_Complex"); continue; }
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy406;
	}
yy406:
	{ PRINT_TOKEN("_Generic"); continue; }
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy423;
		default: goto yy43;
	}
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy424;
		default: goto yy43;
	}
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy426;
		default: goto yy43;
	}
yy410:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy427;
		default: goto yy43;
	}
yy411:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy412;
	}
yy412:
	{ PRINT_TOKEN("__func__"); continue; }
yy413:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy414;
	}
yy414:
	{ PRINT_TOKEN("continue"); continue; }
yy415:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy416;
	}
yy416:
	{ PRINT_TOKEN("register"); continue; }
yy417:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy418;
	}
yy418:
	{ PRINT_TOKEN("restrict"); continue; }
yy419:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy420;
	}
yy420:
	{ PRINT_TOKEN("unsigned"); continue; }
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy422;
	}
yy422:
	{ PRINT_TOKEN("volatile"); continue; }
yy423:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy428;
		default: goto yy43;
	}
yy424:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy425;
	}
yy425:
	{ PRINT_TOKEN("_Noreturn"); continue; }
yy426:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy430;
		default: goto yy43;
	}
yy427:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy431;
		default: goto yy43;
	}
yy428:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy429;
	}
yy429:
	{ PRINT_TOKEN("_Imaginary"); continue; }
yy430:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy432;
		default: goto yy43;
	}
yy431:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy433;
		default: goto yy43;
	}
yy432:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy434;
		default: goto yy43;
	}
yy433:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy435;
		default: goto yy43;
	}
yy434:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy436;
		default: goto yy43;
	}
yy435:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy437;
		default: goto yy43;
	}
yy436:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy439;
		default: goto yy43;
	}
yy437:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy438;
	}
yy438:
	{ PRINT_TOKEN("_Thread_local"); continue; }
yy439:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy42;
		default: goto yy440;
	}
yy440:
	{ PRINT_TOKEN("_Static_assert"); continue; }
}

  }

  return 0;
}

int main() {
  const char* str = R"~(// Test C language(C11) lexer.
    #include <stdio.h> 
    /* hello world example. */
    int main(){ 
      printf("hello world\n");
      return 0; 
    }
  )~";
  assert(lex(str));
  return 0;
}
